name: Deploy Vite React App

on:
  push:
    branches:
      - master # Adjust if your default branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no bitnami@13.127.116.15 << 'EOF'
            # Clone the repository
            if [ -d "React-Notes-app" ]; then
              cd React-Notes-app
              git pull origin main
            else
              git clone https://github.com/HarshAgrawalSB/React-Notes-app.git
              cd React-Notes-app
            fi

            # Install dependencies
            npm install

            # Start the Vite development server
            npm run dev -- --host &

            # Start ngrok to expose the app
            ngrok http 5173 &
          EOF
